Repository Constellation-Labs/tessellation, pull requests merged in 2021-10, with the labels that each got.

#26 Change a Topic to unterminated Queue for joining flow
  modules/core/src/main/scala/org/tesselation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/storage/NodeStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/node/NodeStorage.scala
  modules/shared/src/main/scala/org/tesselation/schema/node.scala
Labels: fix

#27 Badges in readme
  README.md
Labels: other

#23 Introduce kernel module with basic types
  .gitignore
  build.sbt
  modules/kernel/src/main/scala/org/tesselation/kernel/Cell.scala
  modules/kernel/src/main/scala/org/tesselation/kernel/Hom.scala
  modules/kernel/src/main/scala/org/tesselation/kernel/PipeArrow.scala
  modules/kernel/src/main/scala/org/tesselation/kernel/Stack.scala
  modules/kernel/src/main/scala/org/tesselation/kernel/ΩList.scala
  modules/kernel/src/test/scala/org/tesselation/kernel/CellMonoidLawsSuite.scala
  modules/kernel/src/test/scala/org/tesselation/kernel/CellMonoidManualTestSuite.scala
  modules/kernel/src/test/scala/org/tesselation/kernel/ΩListSuite.scala
Labels: feature

#29 Quill, Doobie setup with Address DB layer
  build.sbt
  modules/core/src/main/scala/org/tesselation/Main.scala
  modules/core/src/main/scala/org/tesselation/config/Config.scala
  modules/core/src/main/scala/org/tesselation/config/types.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/storage/AddressStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/services/Cluster.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/storage/AddressStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/db/DoobieTransactor.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/db/context/AddressDBContext.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/db/schema.scala
  modules/core/src/main/scala/org/tesselation/resources/AppResources.scala
  modules/shared/src/main/scala/org/tesselation/schema/address.scala
  project/Dependencies.scala
Labels: feature

#35 Fix logging
  project/Dependencies.scala
Labels: fix

#38 Prometheus metrics
  build.sbt
  modules/core/src/main/scala/org/tesselation/http/routes/MetricRoutes.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/metrics/Atomic.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/metrics/Metrics.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/metrics/MetricsRegistry.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/metrics/types.scala
  modules/core/src/main/scala/org/tesselation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tesselation/modules/Services.scala
  project/Dependencies.scala
Labels: feature

#48 Use implicit SecureRandom in SelfSignedCertificate
  modules/keytool/src/main/scala/org/tesselation/keytool/KeyStoreUtils.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/Main.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cert/DistinguishedName.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cert/SelfSignedCertificate.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/config/types.scala
Labels: fix
