Repository Constellation-Labs/tessellation, pull requests merged in 2021-12, with the labels that each got.

#66 Update data generator to new cats, add basic test.
  modules/core/src/test/scala/org/tessellation/trust/DataGenerationSuite.scala
  modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala
Labels: feature

#77 Use decline for core CLI layer
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/config.scala
  modules/core/src/main/scala/org/tessellation/cli/db.scala
  modules/core/src/main/scala/org/tessellation/cli/http.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/cli/parser.scala
  modules/core/src/main/scala/org/tessellation/config/Config.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/logs/LoggerConfigurator.scala
  modules/shared/src/main/scala/org/tessellation/ext/decline/decline.scala
  project/Dependencies.scala
Labels: feature

#80 Directed Acylic Transitive Trust implementation
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/DATT.scala
  modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
  modules/core/src/test/scala/org/tessellation/trust/TrustCalculationSuite.scala
Labels: feature

#78 Snapshot aggregation
  build.sbt
  examples/empty/build.sbt
  examples/empty/project/Dependencies.scala
  examples/empty/src/main/resources/state-channel-def
  examples/empty/src/main/resources/state-channel-manifest.json
  examples/empty/src/main/scala/org/example/Empty.scala
  examples/empty/src/main/scala/org/example/EmptyDef.scala
  examples/empty/src/main/scala/org/example/EmptyInput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelInstance.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelManifest.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelOutput.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelContextLoader.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelRouter.scala
  modules/core/src/main/scala/org/tessellation/modules/Queues.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/HypergraphContext.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelContext.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelDef.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
Labels: feature

#85 SDK and DAG-L1 modules
  build.sbt
  modules/dag-l1/src/main/resources/.gitkeep
  modules/dag-l1/src/main/scala/org/tessellation/.gitkeep
  modules/sdk/src/main/resources/.gitkeep
  modules/sdk/src/main/scala/org/tessellation/.gitkeep
Labels: other

#87 Example state channel snapshot in L0 cell
  examples/l0-token/src/main/scala/org/example/L0TokenDef.scala
  examples/l0-token/src/main/scala/org/example/types.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelSnapshot.scala
Labels: feature

#86 DAG state channel transaction validator
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/TransactionValidator.scala
Labels: feature

#83 Implement compound model - EigenTrust / DATT / SAW & Tests
  build.sbt
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/DATT.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/EigenTrust.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/SelfAvoidingWalk.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustModel.scala
  modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala
  modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
  modules/core/src/test/scala/org/tessellation/trust/TrustCalculationSuite.scala
Labels: feature

#88 DAG state channel block validator
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/filter/Consecutive.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/types/BlockReference.scala
Labels: feature

#90 Ignore non deterministic sybil attack test
  modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
Labels: test

#89 DAG state channel refined types and access modifiers in block validator
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
Labels: fix

#96 Move cluster and session storages to SDK package
  build.sbt
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/PeerDiscovery.scala
  modules/core/src/main/scala/org/tessellation/http/routes/ClusterRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/cluster/rumour/handler.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/cluster/services/Cluster.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/cluster/services/Session.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/gossip/GossipDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/gossip/RumorHandlers.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/.gitkeep
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/SessionStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/SessionStorage.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorageSuite.scala
Labels: other

#99 Remove redundant gossip client
  modules/core/src/main/scala/org/tessellation/http/p2p/clients/GossipClient.scala
Labels: fix

#93 DAG state channel transaction service
  modules/dag-l1/src/main/scala/org/tessellation/.gitkeep
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/transaction/TransactionService.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: feature

#100 Move Session service to SDK
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Session.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Session.scala
Labels: other

#101 Move Cluster service to SDK
  modules/core/src/main/scala/org/tessellation/cli/http.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tessellation/http/routes/RegistrationRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/resources/MkHttpClient.scala
  modules/core/src/main/scala/org/tessellation/resources/MkHttpServer.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
Labels: other

#102 Use P2P sign client directly in joining flow
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
Labels: other

#103 Move joining flow to SDK
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/core/src/main/scala/org/tessellation/http/routes/ClusterRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/logs/LoggerConfigurator.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/AppEnvironment.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/ClusterClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SignClient.scala
Labels: other

#95 DAG state channel block service
  build.sbt
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/TipsConfig.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/Tips.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/BlockReference.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
Labels: feature

#104 DAG state channel move transaction service to domain
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/transaction/TransactionService.scala
Labels: fix

#107 Base TessellationIOApp
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/effect/package.scala
  modules/shared/src/main/scala/org/tessellation/ext/codecs.scala
  modules/shared/src/main/scala/org/tessellation/ext/crypto.scala
  modules/shared/src/main/scala/org/tessellation/ext/kryo.scala
  modules/shared/src/main/scala/org/tessellation/ext/refined.scala
Labels: feature

#106 DAG state channel block consensus mechanism
  build.sbt
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/AlgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusOutput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CancellationReason.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CoalgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/config/ConsensusConfig.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/http/p2p/clients/BlockConsensusClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/storage/ConsensusStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/round.scala
Labels: feature
