Repository Constellation-Labs/tessellation, pull requests merged in 2021-11, with the labels that each got.

#57 Create transaction method for wallet
  build.sbt
  modules/shared/src/main/scala/org/tesselation/crypto/ops/package.scala
  modules/shared/src/main/scala/org/tesselation/schema/package.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/Main.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/cli/env.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/cli/method.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/transaction/io.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/transaction/package.scala
  project/Dependencies.scala
Labels: feature

#58 Get rid of cyclic dependencies
  build.sbt
  modules/core/src/main/scala/org/tesselation/Main.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/services/Cluster.scala
  modules/core/src/main/scala/org/tesselation/domain/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/http/p2p/clients/SignClient.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/services/Cluster.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/Gossip.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/GossipDaemon.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/modules/Daemons.scala
  modules/core/src/main/scala/org/tesselation/modules/Programs.scala
  modules/core/src/main/scala/org/tesselation/modules/Services.scala
  modules/core/src/main/scala/org/tesselation/package.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/KeyPairGenerator.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/KeyStoreUtils.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/Main.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cert/SelfSignedCertificate.scala
  modules/shared/src/main/scala/org/tesselation/cli/env.scala
  modules/shared/src/main/scala/org/tesselation/ext/crypto.scala
  modules/shared/src/main/scala/org/tesselation/schema/address.scala
  modules/shared/src/main/scala/org/tesselation/schema/gossip.scala
  modules/shared/src/main/scala/org/tesselation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tesselation/schema/peer.scala
  modules/shared/src/main/scala/org/tesselation/schema/transaction.scala
  modules/shared/src/main/scala/org/tesselation/security/Base58.scala
  modules/shared/src/main/scala/org/tesselation/security/Encodable.scala
  modules/shared/src/main/scala/org/tesselation/security/Hash.scala
  modules/shared/src/main/scala/org/tesselation/security/Hex.scala
  modules/shared/src/main/scala/org/tesselation/security/SecureRandom.scala
  modules/shared/src/main/scala/org/tesselation/security/SecurityProvider.scala
  modules/shared/src/main/scala/org/tesselation/security/key/ops.scala
  modules/shared/src/main/scala/org/tesselation/security/key/package.scala
  modules/shared/src/main/scala/org/tesselation/security/security.scala
  modules/shared/src/main/scala/org/tesselation/security/signature/Signed.scala
  modules/shared/src/main/scala/org/tesselation/security/signature/Signing.scala
  modules/shared/src/main/scala/org/tesselation/security/signature/signature.scala
  modules/shared/src/test/scala/org/tesselation/crypto/SignedSuite.scala
  modules/shared/src/test/scala/org/tesselation/schema/TransactionSuite.scala
  modules/shared/src/test/scala/org/tesselation/security/Base58Suite.scala
  modules/shared/src/test/scala/org/tesselation/security/generators.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/Main.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/transaction/io.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/transaction/package.scala
Labels: fix

#59 Switch from scopt to decline in keytool
  build.sbt
  modules/keytool/src/main/scala/org/tesselation/keytool/Main.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cli/config.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cli/method.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/cli/parser.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/config/KeytoolConfig.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/config/types.scala
  modules/shared/src/main/scala/org/tesselation/cli/env.scala
  modules/shared/src/main/scala/org/tesselation/ext/decline/WithOpts.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/Main.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/cli/env.scala
  modules/wallet/src/main/scala/org/tesselation/wallet/cli/method.scala
Labels: fix

#60 Use Hex newtype instead of String
  modules/core/src/main/scala/org/tesselation/package.scala
  modules/core/src/test/scala/org/tesselation/infrastructure/cluster/storage/ClusterStorageSuite.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/KeyStoreUtils.scala
  modules/keytool/src/main/scala/org/tesselation/keytool/Main.scala
  modules/shared/src/main/scala/org/tesselation/schema/id.scala
  modules/shared/src/main/scala/org/tesselation/schema/peer.scala
  modules/shared/src/main/scala/org/tesselation/security/Hex.scala
  modules/shared/src/main/scala/org/tesselation/security/key/ops.scala
  modules/shared/src/main/scala/org/tesselation/security/key/package.scala
  modules/shared/src/main/scala/org/tesselation/security/security.scala
  modules/shared/src/main/scala/org/tesselation/security/signature/signature.scala
  modules/shared/src/test/scala/org/tesselation/crypto/SignedSuite.scala
  modules/shared/src/test/scala/org/tesselation/schema/OpticsSuite.scala
  modules/shared/src/test/scala/org/tesselation/schema/generators.scala
Labels: fix

#56 Gossip counter and session verification
  modules/core/src/main/scala/org/tesselation/config/Config.scala
  modules/core/src/main/scala/org/tesselation/config/types.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/storage/ClusterStorage.scala
  modules/core/src/main/scala/org/tesselation/domain/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/daemon/NodeStateDaemon.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/rumour/handler.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/cluster/storage/ClusterStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/Gossip.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/GossipDaemon.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorHandler.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorHandlers.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/package.scala
  modules/core/src/main/scala/org/tesselation/modules/Programs.scala
  modules/core/src/main/scala/org/tesselation/modules/Services.scala
  modules/shared/src/main/scala/org/tesselation/ext/refined.scala
  modules/shared/src/main/scala/org/tesselation/schema/gossip.scala
  modules/shared/src/main/scala/org/tesselation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tesselation/schema/node.scala
  modules/shared/src/main/scala/org/tesselation/schema/package.scala
  modules/shared/src/main/scala/org/tesselation/security/signature/Signed.scala
Labels: feature

#55 ACI Classpath loading
  examples/empty/.gitignore
  examples/empty/build.sbt
  examples/empty/project/Dependencies.scala
  examples/empty/project/build.properties
  examples/empty/src/main/resources/state-channel-manifest.json
  examples/empty/src/main/scala/org/example/Empty.scala
  modules/core/src/main/scala/org/tesselation/domain/aci/StateChannelContext.scala
  modules/core/src/main/scala/org/tesselation/domain/aci/StateChannelInput.scala
  modules/core/src/main/scala/org/tesselation/domain/aci/StateChannelManifest.scala
  modules/core/src/main/scala/org/tesselation/domain/aci/StateChannelRouter.scala
  modules/core/src/main/scala/org/tesselation/domain/aci/package.scala
  modules/core/src/main/scala/org/tesselation/http/routes/StateChannelRoutes.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/aci/StateChannelContextLoader.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/aci/StateChannelRouter.scala
  modules/core/src/main/scala/org/tesselation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tesselation/modules/Services.scala
  modules/shared/src/main/scala/org/tesselation/schema/address.scala
Labels: feature

#62 Fix JSON manifest loading
  examples/empty/src/main/resources/state-channel-manifest.json
  modules/core/src/main/scala/org/tesselation/infrastructure/aci/StateChannelContextLoader.scala
Labels: fix

#64 CellMonoid test syntax fix
  modules/kernel/src/test/scala/org/tesselation/kernel/CellMonoidManualTestSuite.scala
Labels: test

#65 Enable model with simple transitive test.
  modules/core/src/main/scala/org/tesselation/infrastructure/trust/SelfAvoidingWalk.scala
  modules/core/src/test/scala/org/tesselation/trust/TrustCalculationSuite.scala
Labels: feature

#67 Ordering rumors by both generation and counter
  build.sbt
  modules/core/src/main/scala/org/tesselation/Main.scala
  modules/core/src/main/scala/org/tesselation/domain/cluster/programs/Joining.scala
  modules/core/src/main/scala/org/tesselation/domain/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/Gossip.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/GossipDaemon.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorHandler.scala
  modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorStorage.scala
  modules/core/src/main/scala/org/tesselation/modules/Programs.scala
  modules/core/src/main/scala/org/tesselation/modules/Services.scala
  modules/shared/src/main/scala/org/tesselation/schema/gossip.scala
  modules/shared/src/main/scala/org/tesselation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tesselation/schema/peer.scala
  modules/shared/src/main/scala/org/tesselation/security/Hex.scala
  modules/shared/src/test/scala/org/tesselation/schema/RumorSuite.scala
  modules/test-shared/src/main/scala/org/tesselation/syntax/boolean.scala
  project/Dependencies.scala
Labels: feature

#69 Renaming extractor object
  modules/core/src/main/scala/org/tessellation/ext/http4s/vars.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
Labels: fix

#70 Logback configuration for testnet
  modules/core/src/main/resources/logback-testnet.xml
  modules/core/src/main/resources/logback.xml
Labels: other

#72 Add wallet jar file to release flow
  .github/workflows/release.yml
Labels: fix

#73 HypergraphContext with L0 token example
  .gitignore
  build.sbt
  examples/l0-token/.gitignore
  examples/l0-token/.scalafix.conf
  examples/l0-token/.scalafmt.conf
  examples/l0-token/build.sbt
  examples/l0-token/project/Dependencies.scala
  examples/l0-token/project/build.properties
  examples/l0-token/project/plugins.sbt
  examples/l0-token/src/main/resources/state-channel-manifest.json
  examples/l0-token/src/main/scala/org/example/L0Token.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelContext.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelContextLoader.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelRouter.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/cluster/storage/ClusterStorageSuite.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/HypergraphContext.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/ProcessSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelContext.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
Labels: feature

#74 Include kernel kryo into core and cell registrar
  examples/empty/build.sbt
  examples/l0-token/src/main/resources/state-channel-manifest.json
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelContextLoader.scala
  modules/core/src/main/scala/org/tessellation/kryo/package.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/kryo/package.scala
Labels: feature

#75 Update kryo registration for example empty project
  examples/empty/src/main/resources/state-channel-manifest.json
Labels: other
