Repository Constellation-Labs/tessellation, pull requests merged in 2022-10, with the labels that each got.

#465 Prevent drawing the same peer more than once for a gossip round
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
Labels: other

#467 Increase the number of concurrent gossip rounds
  modules/core/src/main/scala/org/tessellation/cli/method.scala
Labels: other

#466 Increase PD HealthCheck timeout
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
Labels: other

#468 Increase consensus timeout to 60s
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
Labels: other

#469 Mainnet seedlist - batch 2
  mainnet/mainnet-seedlist
Labels: other

#471 Fix memory leak in L0 consensus storage
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
Labels: fix

#472 DAG Routes return ordinals as a single value
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
Labels: fix

#473 Update SoftStaking rewards to match the rewards program
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#474 Increase consensus timeout to 2m
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
Labels: other

#475 Mainnet seedlist - batch 3
  mainnet/mainnet-seedlist
Labels: other

#476 Use Supervisor to control lifecycle of spawned Fibers
  modules/core/src/main/scala/org/tessellation/infrastructure/healthcheck/HealthCheckDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/daemon/DownloadDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HealthChecks.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/healthcheck/HealthCheckDaemon.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HealthChecks.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/Daemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/daemon/NodeStateDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/daemon/CollateralDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/daemon/CollateralDaemonSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheckSuite.scala
Labels: fix

#477 Discard old gen rumors
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
Labels: fix

#478 Unidirectional registration
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerRegistration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/RegistrationExchange.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/registration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
Labels: other

#479 Increase DTM rewards and adjust consensus trigger interval
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#480 Metrics should outlive soft restart
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
Labels: fix

#481 Increase DTM rewards and adjust consensus trigger interval
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#482 Fix querying rumors from storage
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
Labels: fix

#484 Fix rumor storage initialization
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
Labels: fix

#488 Add last snapshot hash to GlobalSnapshotReference
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotReference.scala
Labels: other

#491 Update mainnet seedlist - one of ids had invalid characters
  mainnet/mainnet-seedlist
Labels: other

#492 Filter proposed facilitators based on collateral
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
Labels: feature

#493 Fix CL_COLLATERAL env normalization and rumor logging
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CollateralAmountOpts.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
Labels: fix

#496 Filter out zero-balance addresses when creating global snapshot
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
Labels: feature
