Repository Constellation-Labs/tessellation, pull requests merged in 2022-06, with the labels that each got.

#260 Fix facilitator superset calculation & include whitelisting
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerDeclaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerDeclarations.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/message.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/kind.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
Labels: fix

#262 Fix non-stable hash calculation of GlobalSnapshot
  modules/core/src/main/scala/org/tessellation/domain/snapshot/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/BlockReference.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/ActiveTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/BlockAsActiveTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/DeprecatedTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotInfo.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotTips.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/block/BlockValidatorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/data/OrderBasedOrdering.scala
  modules/shared/src/main/scala/org/tessellation/ext/derevo/ordering.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
  modules/shared/src/main/scala/org/tessellation/security/Hashed.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/main/scala/org/tessellation/syntax/SortedCollectionSyntax.scala
  modules/shared/src/main/scala/org/tessellation/syntax/package.scala
  modules/shared/src/test/scala/org/tessellation/crypto/SignedSuite.scala
Labels: fix

#267 Check session while removing peer from ping healthcheck
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckKey.scala
Labels: fix

#266 Added a Setup and Contributing guide.
  CONTRIBUTING.md
  SETUP.md
Labels: other

#268 Decoding proofs to serializable Nes
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: fix

#269 Fix ADR #10 status
  doc/adr/0010-reducing-snapshot-size.md
Labels: fix

#270 Generalized the setup instructions to be OS agnostic
  SETUP.md
Labels: other

#273 Fix sortRumors cast type in gossip
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: fix

#274 Check data equality when adding proofs for Signed
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
  modules/shared/src/test/scala/org/tessellation/crypto/SignedSuite.scala
Labels: fix

#276 Fix typo causing 60s delay on L1 API
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/middlewares/X-Id.scala
Labels: fix

#275 Fix draining l1 consensus pipeline twice
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
Labels: fix

#280 Add dependency updates plugin
  project/plugins.sbt
Labels: other

#283 Add jvmopts for faster compilation
  .jvmopts
Labels: other

#278 Queue proposals for future healthcheck rounds
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
Labels: fix

#286 Log error on peer discovery
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
Labels: fix

#287 Fix port number in README.md
  README.md
Labels: ignore

#288 Tools improvement: log time & chunk min size
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/TransactionGenerator.scala
Labels: ignore

#289 Log only summary for block consensus inputs
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
Labels: other

#284 GET transaction endpoint on L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/shared/src/main/scala/org/tessellation/ext/http4s/HashVar.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/security/Hashed.scala
Labels: feature

#290 Remove ip checking from p2p middleware
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Session.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/middlewares/PeerAuthMiddleware.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Session.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
Labels: fix

#293 Healthcheck - request missing proposals
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/HealthChecks.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HealthChecks.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckRoundId.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HistoricalRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealth.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerProposalHealthcheckRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/kind.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/handler.scala
Labels: feature

#295 Healthcheck - check if proposal exists
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
Labels: feature

#292 Only allow blocks with non empty transactions set
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CancellationReason.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceLogic.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/TransactionChainValidator.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/block/BlockValidatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/ext/codecs.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: fix

#297 Fix logging awaiting blocks
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceManager.scala
Labels: fix

#300 Send signatures instead of blocks in L1 consensus
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/AlgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CoalgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: fix

#298 Eks setup instructions
  SETUP.md
Labels: ignore

#296 Grafana and Prometheus
  build.sbt
  kubernetes/base/deployment.yaml
  kubernetes/grafana/dashboards/dashboards.yaml
  kubernetes/grafana/dashboards/jvm-micrometer_rev9.json
  kubernetes/grafana/dashboards/tessellation.json
  kubernetes/grafana/datasources/datasource.yaml
  kubernetes/grafana/grafana-deployment.yaml
  kubernetes/grafana/grafana-service.yaml
  kubernetes/grafana/grafana.ini
  kubernetes/grafana/kustomization.yaml
  kubernetes/prometheus/kustomization.yaml
  kubernetes/prometheus/prometheus-deployment.yaml
  kubernetes/prometheus/prometheus-service.yaml
  kubernetes/prometheus/prometheus.yaml
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/routes/MetricRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/metrics/Atomic.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/metrics/Metrics.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/metrics/MetricsRegistry.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/metrics/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/MetricRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/TargetRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/metrics.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/metrics/Metrics.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  skaffold.yaml
Labels: feature

#301 Update scalafmt.
  .scalafmt.conf
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Session.scala
Labels: ignore

#303 Consistent empty hash
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
Labels: fix

#302 Tool - ability to send sample state-channel snapshot
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/TransactionGenerator.scala
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
Labels: other

#305 Don't rehash transactions during pull
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/filter/Consecutive.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: fix

#307 Add docker push to skaffold build
  SETUP.md
  skaffold.yaml
Labels: ignore

#309 Reference an empty Hash for the very first state channel snapshot
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
Labels: fix

#310 Tool - fix state channel POST endpoint
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: other

#294 Add collateral verification in Joining.
  kubernetes/base/deployment.yaml
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/types.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CollateralAmountOpts.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/collateral/Collateral.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/collateral/LatestBalances.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
Labels: feature

#299 Add collateral verification to p2p.
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/middlewares/PeerAuthMiddleware.scala
Labels: feature

#315 Adding peer_id_short label
  kubernetes/grafana/dashboards/tessellation.json
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/TargetRoutes.scala
  modules/shared/src/main/scala/org/tessellation/security/Hex.scala
Labels: other

#304 Add collateral verification to gossip daemon
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: feature

#316 Add default balance for not found addresses when checking collateral
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
Labels: fix

#318 Majority on trigger type
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/trigger.scala
Labels: feature

#313 Add collateral verification for blocks
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
Labels: feature

#319 Fix not registered trigger classes
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
Labels: fix
