Repository Constellation-Labs/tessellation, pull requests merged in 2022-09, with the labels that each got.

#410 Use all known round ids when resolving health proposals
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthcheckRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckRoutes.scala
Labels: fix

#411 Fix active retention time & log deactivation
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/metrics.scala
Labels: fix

#409 Log joining rejection reason.
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SignClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
Labels: other

#412 Http4s client request & response logging
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/SdkResources.scala
  modules/shared/src/main/resources/logback-included.xml
Labels: other

#414 Bloop based BSP configuration for IntelliJ
  .gitignore
  build.sbt
  project/plugins.sbt
Labels: ignore

#413 Turn off http client logger on Dev environment
  modules/shared/src/main/resources/logback.xml
Labels: other

#415 Request healthcheck proposal with sending own proposal
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthcheckRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckRoutes.scala
Labels: feature

#419 Make node state endpoint public
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
Labels: feature

#416 Healthcheck - send all round ids inside the proposal
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensusDriver.scala
Labels: fix

#417 Healthcheck - remove unused misleading fn for getting round ids
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
Labels: other

#418 Healthcheck - handle proposal for round in progress first
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
Labels: fix

#420 Remove old peer data before rejoining
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
Labels: fix

#421 Gossip deregistration request before leaving the cluster
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/RegistrationExchange.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: fix

#422 Fix snapshot processor condition for new height
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
Labels: fix

#423 Threshold for skipping and awaiting in peer declaration rounds
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: fix

#424 Gossip JSON streams
  build.sbt
  kubernetes/grafana/dashboards/tessellation.json
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelOutput.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Queues.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/http/p2p/clients/BlockConsensusClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0DAGClusterClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Queues.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/ActiveTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/BlockAsActiveTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/DeprecatedTip.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotTips.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckRoundId.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/PeerResponse.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SignClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/RegistrationExchange.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/message.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/trigger.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/metrics.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/p2p/GossipClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkQueues.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  project/Dependencies.scala
Labels: feature

#425 Temporarily disable starting healthcheck round on gossip error
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: fix

#428 Generation data type
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/generation.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
Labels: feature

#427 Use graph based facilitator discovery mechanism
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculator.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculatorSuite.scala
Labels: feature

#429 Use Generation for peer's SessionToken
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/headers/X-Session-Token.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/SessionStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/generation.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#430 Format FacilitatorCalculatorSuite
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculatorSuite.scala
Labels: other

#434 Log failed gossip with warn level
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: other

#433 Fix short format for Hex class
  modules/shared/src/main/scala/org/tessellation/security/Hex.scala
Labels: fix

#432 Filter out invalid majority snapshot signatures
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
Labels: fix

#431 Endpoint for getting ClusterSessionToken
  build.sbt
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
Labels: feature

#436 Ping healthcheck can be explicitly enabled/disabled
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
Labels: feature

#437 New generation-based peer session used for joining
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/ClusterClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/TargetRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/healthcheck.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/test/scala/org/tessellation/schema/OpticsSuite.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#435 Use rumor ordinals for diff calculation
  kubernetes/base/deployment.yaml
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/metrics.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/p2p/GossipClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/metrics/Metrics.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkStorages.scala
  modules/shared/src/main/scala/org/tessellation/ext/refined/refined.scala
  modules/shared/src/main/scala/org/tessellation/schema/generation.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: other

#438 Node Info endpoint
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
Labels: feature

#439 Fix for discovering L0 peers
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0ClusterClient.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: fix

#440 Local healthcheck
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/LocalHealthcheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/NodeClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
  project/Dependencies.scala
Labels: feature

#441 Fix configurable ping healthcheck
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
Labels: fix

#442 Fix local healthcheck output action
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheck.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheckSuite.scala
Labels: fix

#445 Disable ping healthcheck on L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
Labels: other

#444 More verbose node info
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: feature

#446 Add cluster session to node info endpoint
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: other

#448 Log gossip errors with error classname
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: fix

#443 Log consensus signature validation on warn and status change on info
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
Labels: other

#449 Consensus metrics for duration and proposal affinity
  kubernetes/grafana/dashboards/tessellation.json
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/metrics/Metrics.scala
Labels: other

#451 Fix cancelling local healthcheck
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheck.scala
Labels: fix

#453 Glogal snapshot json endpoint
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/shared/src/main/scala/org/tessellation/ext/http4s/headers/negotiation.scala
Labels: feature

#450 Consensus registration and deregistration improvements
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerRegistration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: fix

#454 Temporarily disable state channel events for mainnet
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
Labels: feature

#452 Use coinbase hash in genesis snapshot
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/Coinbase.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/snapshot/CoinbaseSuite.scala
Labels: feature

#456 Lower initial tip count from 16 to 8
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
Labels: fix

#455 Hardcode next facilitators
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
Labels: fix

#457 L0 & L1 uptime panels
  kubernetes/grafana/dashboards/tessellation.json
Labels: other

#458 Add mainnet-seedlist to release flow
  .github/workflows/release.yml
  mainnet/mainnet-seedlist
Labels: other

#459 Fix peer registration exchange flow
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: fix

#461 Reorder program rewards
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
Labels: fix

#464 Fix local calculation of consensus duration
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: fix

#463 Split stardust rewards into two addresses
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/StardustCollectiveDistributor.scala
Labels: other

#462 Update tessellation dashboard with mainnet edits
  README.md
  SETUP.md
  kubernetes/grafana/dashboards/tessellation.json
  kubernetes/grafana/grafana-deployment.yaml
  kubernetes/grafana/grafana-service.yaml
  kubernetes/nginx/http-proxy-service.yaml
  skaffold.yaml
Labels: ignore
