Repository Constellation-Labs/tessellation, pull requests merged in 2022-05, with the labels that each got.

#231 Ping healtheck - outcome actions
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/modules/HealthChecks.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HealthChecks.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckConsensusDecision.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDecision.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensusDecision.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
Labels: feature

#235 Add RewardTransaction to kryo registrar.
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: fix

#237 Fix hash calculation for global snapshot consensus
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
Labels: fix

#234 L0 Cell for L1 data and StateChannelSnapshot entrypoint
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelGistedOutput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelInput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelInstance.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelOutput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelRunner.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/package.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/AlgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/CoalgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/L0Cell.scala
  modules/core/src/main/scala/org/tessellation/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelRunner.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/main/scala/org/tessellation/package.scala
Labels: feature

#233 L1 download/redownload and tips handling
  build.sbt
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/address/storage/AddressStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/services/L0Service.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotOrdinalStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotReference.scala
  modules/shared/src/main/scala/org/tessellation/ext/fs2.scala
Labels: feature

#239 Fix missing class registration and block routes
  modules/core/src/main/scala/org/tessellation/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
Labels: fix

#240 Move L1-output endpoint to DAG Routes
  modules/core/src/main/scala/org/tessellation/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0DAGClusterClient.scala
Labels: fix

#241 Fix snapshot data trigger
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotTriggerPipeline.scala
Labels: fix

#242 Prevent empty blocks
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
Labels: other

#243 Fix invalid rebase
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
Labels: fix

#244 Tools for testing transaction flow
  build.sbt
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
Labels: other

#245 Add missing endpoints
  modules/core/src/main/scala/org/tessellation/ext/http4s/SnapshotOrdinalVar.scala
  modules/core/src/main/scala/org/tessellation/ext/http4s/vars.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/shared/src/main/scala/org/tessellation/ext/http4s/AddressVar.scala
  modules/shared/src/main/scala/org/tessellation/ext/http4s/queryParam.scala
Labels: feature

#248 Remove balance validation from transaction endpoint
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/ContextualTransactionValidator.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/transaction/ContextualTransactionValidatorSuite.scala
Labels: fix

#249 Keep snapshot in memory when offloading fails
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
Labels: fix

#253 Increase snapshot time-trigger interval
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
Labels: other

#255 Include DAG L1 in build pipeline
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
Labels: fix

#254 Spread ping-healthcheck proposal as PeerRumor instead of CommonRumor
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/handler.scala
Labels: fix

#256 Handle peer-declaration healthcheck proposal as PeerRumor instead of CommonRumor
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
Labels: fix

#257 Fixes for healthcheck determinism
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HistoricalRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/handler.scala
Labels: fix

#258 Facilitator superset and facilitator synchronous removal
  README.md
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/message.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  skaffold.yaml
Labels: feature

#250 Reducing the global snapshot size ADR
  doc/adr/0010-reducing-snapshot-size.md
Labels: adr

#139 Project versioning and release flow ADR
  doc/adr/0011-project-versioning-and-release-flow.md
Labels: adr
