Repository Constellation-Labs/tessellation, pull requests merged in 2022-02, with the labels that each got.

#149 Cluster leave and peer removal capabilities
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: feature

#150 Remove leaving or offline peer
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
Labels: feature

#153 Handle block storing error in DAG L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
Labels: fix

#154 DAG state channel infrastructure and startup flow
  build.sbt
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/db.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/http.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/TipsConfig.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/types.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/config/ConsensusConfig.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/db/Database.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/db/Migrations.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/kryo/package.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Queues.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/config/BlockValidatorConfig.scala
  project/Dependencies.scala
Labels: feature

#155 Healthcheck round inspection and outcome action
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheckRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/services/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: feature

#156 Parametric HealthCheck key and status
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheckRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/services/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckRoundId.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckRoundType.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HistoricalRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/types.scala
Labels: feature

#157 Cluster info endpoint
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/middlewares/X-Id.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  project/Dependencies.scala
Labels: feature

#160 Remove Unknown node state and fix switching to Ready state
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/shared/src/main/scala/org/tessellation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
Labels: fix

#159 Healthcheck - round start
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheckRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/services/HealthCheckConsensus.scala
Labels: feature

#161 Time based clean up mechanism for DAG L1 block consensus
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/AlgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusOutput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CoalgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/config/ConsensusConfig.scala
Labels: feature

#151 Time-based snapshot trigger
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/l0/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/l0/config/SnapshotConfig.scala
  modules/core/src/main/scala/org/tessellation/l0/domain/snapshot/GlobalSnapshot.scala
  modules/core/src/main/scala/org/tessellation/l0/domain/snapshot/SnapshotService.scala
  modules/core/src/main/scala/org/tessellation/l0/domain/snapshot/SnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/l0/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/l0/infrastructure/snapshot/SnapshotService.scala
  modules/core/src/main/scala/org/tessellation/l0/schema/snapshot.scala
  modules/shared/src/main/scala/org/tessellation/ext/fs2.scala
Labels: feature

#164 Common rumors
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/block/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
  modules/shared/src/main/scala/org/tessellation/syntax/boolean.scala
  modules/shared/src/test/scala/org/tessellation/schema/RumorOrdinalSuite.scala
Labels: feature

#162 Healthcheck - consensus round logic
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheckRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckConsensusDecision.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckRoundId.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckRoundType.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HistoricalRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckRoundId.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/types/HealthCheckStatus.scala
Labels: feature

#166 Bump scala version to 2.13.8 and remove unused implicits
  build.sbt
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/core/src/main/scala/org/tessellation/l0/infrastructure/snapshot/SnapshotService.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/Gossip.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/shared/src/main/scala/org/tessellation/ext/decline/decline.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  project/Dependencies.scala
Labels: other

#163 Healthcheck - ping consensus implementation
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/healthcheck/HealthCheckDaemon.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HealthChecks.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusRounds.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckConsensusDecision.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HistoricalRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/HealthRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/HealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensusDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/http/routes/HealthRoutesSuites.scala
Labels: feature

#115 ADRs for snapshots
  doc/adr/0002-global-and-state-channel-snapshots.md
  doc/adr/0003-dag-l1-responsibility-and-l0-interconnection.md
  doc/adr/0004-global-snapshot-trigger.md
  doc/adr/0005-joining-pool.md
  doc/adr/0006-selecting-facilitators.md
Labels: adr

#168 Fix order of ADRs
  doc/adr/0004-global-snapshot-trigger.md
  doc/adr/0006-selecting-facilitators.md
  doc/adr/0007-global-and-state-channel-snapshots.md
  doc/adr/0008-dag-l1-responsibility-and-l0-interconnection.md
Labels: adr

#169 Fix doubled node state changes
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/node/NodeStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/node/NodeStorage.scala
Labels: fix

#170 Refactor self origin parameter
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/block/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/OriginPolicy.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
Labels: fix

#173 Syntax for Next[A]
  modules/shared/src/main/scala/org/tessellation/ext/cats/kernel/package.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/NextSyntax.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/package.scala
Labels: other

#172 Storage for GlobalSnapshot
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/l0/domain/snapshot/SnapshotService.scala
  modules/core/src/main/scala/org/tessellation/l0/domain/snapshot/SnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/l0/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/l0/infrastructure/snapshot/SnapshotService.scala
  modules/core/src/main/scala/org/tessellation/l0/schema/snapshot.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/kryo/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/dag.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotWrapper.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/NextSyntax.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
  modules/shared/src/main/scala/org/tessellation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
Labels: feature

#175 Fix DAG L1 kryo registrar numbering
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/kryo/package.scala
Labels: fix

#178 Consistent config names
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
Labels: other

#177 Fix double joining
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SignClient.scala
Labels: fix

#176 ADR for Kryo class registration policy
  doc/adr/0009-kryo-class-registration-policy.md
Labels: adr

#183 Update cats and cats-effect dependencies
  project/Dependencies.scala
Labels: other

#182 Adjust kryo registration ids to ADR #9
  doc/adr/0009-kryo-class-registration-policy.md
  examples/empty/project/Dependencies.scala
  examples/empty/src/main/scala/org/example/EmptyDef.scala
  examples/l0-token/project/Dependencies.scala
  examples/l0-token/src/main/scala/org/example/L0TokenDef.scala
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
  modules/core/src/main/scala/org/tessellation/kryo/package.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/kryo/package.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelDef.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/kryo/package.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/kryo/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/kryo/package.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/test/scala/org/tessellation/schema/TransactionSuite.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala
Labels: fix

#174 L0 peers discovery functionality
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/L0PeerOpts.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/L0ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0ClusterClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/L0ClusterStorage.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/data/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: feature

#185 ADR #9 update
  doc/adr/0009-kryo-class-registration-policy.md
Labels: adr

#186 Adjust kryo registration ids to updated ADR #9
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: fix

#180 State channel output gist
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelGistedOutput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelOutput.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/package.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/SnapshotTrigger.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/core/src/test/scala/org/tessellation/domain/aci/StateChannelOutputGistedSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotBinary.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotWrapper.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/Gistable.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandler.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
Labels: feature

#187 L0 global majority snapshot endpoints
  modules/core/src/main/scala/org/tessellation/ext/http4s/vars.scala
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotBinary.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
Labels: feature

#190 GlobalSnapshot persistent storage
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLocalFileSystemStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotTriggerPipeline.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/kernel/package.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/PartialPreviousSyntax.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/package.scala
  modules/shared/src/main/scala/org/tessellation/storage/DiskSpace.scala
  modules/shared/src/main/scala/org/tessellation/storage/FileSystemStorage.scala
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
  project/Dependencies.scala
Labels: feature

#188 Global snapshot consensus
  examples/empty/build.sbt
  examples/empty/project/Dependencies.scala
  examples/empty/src/main/resources/state-channel-def
  examples/empty/src/main/scala/org/example/EmptyDef.scala
  examples/empty/src/main/scala/org/example/EmptyInput.scala
  examples/simple-snapshot-publisher/.gitignore
  examples/simple-snapshot-publisher/README.md
  examples/simple-snapshot-publisher/build.sbt
  examples/simple-snapshot-publisher/project/Dependencies.scala
  examples/simple-snapshot-publisher/project/build.properties
  examples/simple-snapshot-publisher/project/plugins.sbt
  examples/simple-snapshot-publisher/src/main/resources/state-channel-def
  examples/simple-snapshot-publisher/src/main/scala/org/example/EmitSimpleSnapshot.scala
  examples/simple-snapshot-publisher/src/main/scala/org/example/GenerateInputApp.scala
  examples/simple-snapshot-publisher/src/main/scala/org/example/SimpleSnapshot.scala
  examples/simple-snapshot-publisher/src/main/scala/org/example/SimpleSnapshotPublisherDef.scala
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/aci/StateChannelOutput.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelRunner.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLocalFileSystemStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotTriggerPipeline.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotInfo.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotBinary.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/Daemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerDeclaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/message.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/syntax/NextSyntax.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: feature

#192 Fix missing type parameters
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
Labels: fix

#191 Genesis balances
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
Labels: feature
