Repository Constellation-Labs/tessellation, pull requests merged in 2022-12, with the labels that each got.

#507 Tests for consensus unlocking
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerDeclarations.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/update/ConsensusStateUpdateFn.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/update/UnlockConsensusUpdate.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/update/UnlockConsensusUpdateSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/id.scala
  modules/shared/src/main/scala/org/tessellation/security/Hex.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
Labels: test

#509 Adjust trigger interval
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
Labels: other

#508 Adjust DTM weights
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#510 Soft staking for December 2022
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#516 Enable stall detection when consensus is not synchronized
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/update/UnlockConsensusUpdate.scala
Labels: fix

#517 Remove 'block' suffix from generic Signed validation methods
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
Labels: other

#519 StateChannelSnapshotBinary Order implementation to fix serialization issue
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotSerializationSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/StateChannelSnapshotBinary.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: fix

#520 Grafana dashboard sync
  kubernetes/grafana/dashboards/tessellation.json
  kubernetes/grafana/grafana-deployment.yaml
Labels: other

#511 Validate signed state channel snapshot
  modules/core/src/main/scala/org/tessellation/domain/statechannel/StateChannelService.scala
  modules/core/src/main/scala/org/tessellation/domain/statechannel/StateChannelValidator.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Validators.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelServiceSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/TransactionValidator.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/transaction/ContextualTransactionValidatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
Labels: feature

#514 Fix calculation of last state channel snapshot hashes
  modules/core/src/main/scala/org/tessellation/domain/statechannel/StateChannelValidator.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelServiceSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
Labels: fix

#523 Updated dependencies
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipRoundRunner.scala
  project/Dependencies.scala
Labels: other

#525 Validate kryo registrations
  modules/shared/src/main/scala/org/tessellation/kryo/ExplicitKryoRegistrar.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/test/scala/org/tessellation/kryo/KryoSerializerSuite.scala
Labels: feature

#526 ADR - Modules' structure
  doc/adr/0012-modules-structure.md
Labels: adr

#527 Update scala version to 2.13.10
  build.sbt
  modules/keytool/src/main/scala/org/tessellation/keytool/Main.scala
  modules/shared/src/test/scala/org/tessellation/schema/TransactionSuite.scala
  project/build.properties
  project/plugins.sbt
Labels: other
