Repository Constellation-Labs/tessellation, pull requests merged in 2022-01, with the labels that each got.

#108 SDK configuration and basic flow
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/logs/LoggerConfigurator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/kryo/package.scala
Labels: feature

#109 Use SDK in L0 layer
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/kryo/package.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
Labels: feature

#110 DAG state channel address storage
  build.sbt
  modules/dag-l1/src/main/resources/.gitkeep
  modules/dag-l1/src/main/resources/db.migration/V1__AddressTable.sql
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/address/storage/AddressStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorage.scala
Labels: feature

#113 Ignore non-deterministic data generation unit test
  modules/core/src/test/scala/org/tessellation/trust/DataGenerationSuite.scala
Labels: test

#114 ADR - Architecture decision record
  doc/adr/0001-record-architecture-decisions.md
  doc/adr/TEMPLATE.md
Labels: other

#116 Move shared implicits into separate trait
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
Labels: other

#117 Transaction and Hashed orderings
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/security/Hashed.scala
Labels: feature

#112 DAG state channel new block service
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
Labels: feature

#121 Changelog ADR entry
  .github/config/changelog.json
Labels: other

#119 Move resources to sdk
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/resources/AppResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/MkHttpClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/SdkResources.scala
Labels: other

#120 Service and storage responsibility ADR
  doc/adr/0002-service-and-storage-responsibility.md
Labels: adr

#122 Move modules to SDK
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/main/scala/org/tessellation/modules/Queues.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkQueues.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkStorages.scala
Labels: other

#124 Externalize method checking block consensus readiness
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
Labels: other

#125 Format sybil attack suite class properly
  modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
Labels: other

#126 DAG state channel new transaction service
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
Labels: feature

#123 State-channel endpoint serializer ADR
  doc/adr/0003-state-channel-endpoint-serializer.md
Labels: adr

#129 Rename rumour package to rumor for node state handler
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
Labels: other

#127 DAG state channel http routes and block rumor handler
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/block/rumor/handler.scala
Labels: feature

#134 Add BuildInfo plugin
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/keytool/src/main/scala/org/tessellation/keytool/Main.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala
  project/plugins.sbt
Labels: other

#135 Separate BuildInfo to shared module
  build.sbt
Labels: fix

#136 Initial state for nodes in registration request
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: fix

#133 Fiber definition for DAG Transaction and Block
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
  modules/shared/src/main/scala/org/tessellation/schema/Fiber.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: feature

#131 P2P HTTP verification
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
  build.sbt
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/clients/TrustClient.scala
  modules/core/src/main/scala/org/tessellation/http/routes/ClusterRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/RegistrationRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/services/Session.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/PeerResponse.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/ClusterClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SignClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/headers/X-Id.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/headers/X-Session-Token.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/middlewares/PeerAuthMiddleware.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Session.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/p2p/GossipClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/SdkResources.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: feature

#140 Move functionalities to SDK and refactor trust routes
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/domain/address.scala
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/AppEnvironment.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/HealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/ext/http4s/refined.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/HealthRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/RegistrationRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/daemon/NodeStateDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/HealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/MkHttpServer.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/http/routes/HealthRoutesSuites.scala
Labels: other

#143 Move DAG L1 address table migration file to correct directory
  modules/dag-l1/src/main/resources/db/migration/V1__AddressTable.sql
Labels: fix

#144 Fix checking parent acceptance in DAG L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
Labels: fix

#147 Extract block validator config and allow overriding signers count
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/config/BlockValidatorConfig.scala
Labels: feature

#148 Require single signer in block validation during DAG L1 consensus
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
Labels: fix
