Repository Constellation-Labs/tessellation, pull requests merged in 2022-08, with the labels that each got.

#291 Port over rewards
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/rewards/DTM.scala
  modules/core/src/main/scala/org/tessellation/domain/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/domain/rewards/SoftStaking.scala
  modules/core/src/main/scala/org/tessellation/domain/rewards/StardustCollective.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/DTM.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/SoftStaking.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/StardustCollective.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/epoch.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/schema/id.scala
Labels: feature

#356 Get rid of Math.floorDiv methods
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/DTM.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/StardustCollective.scala
Labels: fix

#357 Fix applying reward transactions for addresses with no balance
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
Labels: fix

#360 Update dependencies versions to newest compatible
  project/Dependencies.scala
  project/plugins.sbt
Labels: fix

#362 Use EpochProgress from previous snapshot for calculating rewards
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
Labels: fix

#364 Throw in case of incorrect calculation of reward distribution
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
Labels: fix

#363 Property tests for SoftStaking and total supply
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
Labels: test

#358 Validate and pick consecutive txs in L1 consensus
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/filter/Consecutive.scala
Labels: feature

#370 Run gossip rounds regardless of local active rumors
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: fix

#368 Observing consensus on join
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/clients/GlobalSnapshotClient.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: feature

#371 Fix declaration healthcheck starting logic
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: fix

#369 Possibility to set starting EpochProgress for Genesis
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
Labels: feature

#372 Fix kryo registation ids
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: fix

#373 Log reward distribution summary
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
Labels: fix

#374 Fix snapshot version to be 0.16.0
  version.sbt
Labels: other

#375 Let snapshot processing fail the stream on error
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
Labels: fix

#376 Add show instance for snapshot processing result
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
Labels: other

#377 Fix ping healthcheck on L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/healthcheck/HealthCheckDaemon.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
Labels: fix

#378 Increase consensus timeout
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
Labels: fix

#379 Gossip round execution improvements
  kubernetes/grafana/dashboards/tessellation.json
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/metrics.scala
  skaffold.yaml
Labels: fix

#380 Consensus debug endpoints
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
Labels: other

#367 Fee distribution rewards
  modules/core/src/main/scala/org/tessellation/domain/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/domain/rewards/RewardsDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/DTMDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Regular.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/RegularDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/SoftStakingDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/StardustCollectiveDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/package.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
Labels: feature

#381 Use short format for logging Id/PeerId
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/main/scala/org/tessellation/security/Hex.scala
Labels: other

#382 Additional logs for transactions
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/shared/src/main/resources/logback-included.xml
Labels: other

#383 Endpoint for L0 peers on L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
Labels: feature

#384 Discover Ready L0 peers only on L1
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala
Labels: fix

#385 Separate logger for transactions
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/package.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/package.scala
  modules/shared/src/main/resources/logback-included.xml
Labels: other

#388 Request healthcheck proposals after delay
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
Labels: fix

#387 Consensus peer registration
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/node/NodeStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/RegistrationExchange.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthcheckRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/node/NodeStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
Labels: feature

#390 Update ubuntu versions in GitHub workflows
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
Labels: ignore

#389 Don't remove nodes with parallel rounds for declaration healthcheck
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDriver.scala
Labels: fix

#393 Improve healthcheck logs
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/kind.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckKey.scala
Labels: other

#392 Use in-memory storage for AddressStorage
  build.sbt
  modules/core/src/main/resources/db/migration/V1__AddressTable.sql
  modules/core/src/main/scala/org/tessellation/domain/cluster/storage/AddressStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/cluster/storage/AddressStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/db/context/AddressDBContext.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/db/schema.scala
  modules/dag-l1/src/main/resources/db/migration/V1.0.0.0__AddressTable.sql
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorageSuite.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#396 Gossip round execution improvements
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
Labels: fix

#395 Logging improvements
  build.sbt
  kubernetes/l0.Dockerfile
  kubernetes/l1.Dockerfile
  kubernetes/logback-kubernetes.xml
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/logs/LoggerConfigurator.scala
  modules/shared/src/main/resources/logback-included.xml
  modules/shared/src/main/resources/logback.xml
  project/Dependencies.scala
Labels: other

#397 Remove tmp logger property
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/logs/LoggerConfigurator.scala
Labels: ignore

#394 Fix stopping processing join requests after one failure
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
Labels: fix

#398 Version check on joining
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: feature

#400 Kubernetes http proxy
  README.md
  kubernetes/grafana/grafana-deployment.yaml
  kubernetes/nginx/http-proxy-service.yaml
  kubernetes/nginx/kustomization.yaml
  kubernetes/nginx/nginx-deployment.yaml
  kubernetes/nginx/nginx.conf
  skaffold.yaml
Labels: other

#401 Log node state with peer availability
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
Labels: other

#402 Fix TimedOut condition in PD HealthCheck
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: fix

#403 Rejoin does not verify all initial joining conditions
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
Labels: fix

#404 Get rid of implicit loggers
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/resources/MkHttpServer.scala
Labels: other

#406 Do not use Show instance for ShowId command
  modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala
Labels: fix

#407 Skip join request stage for rejoining
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
Labels: fix

#408 Peer discovery returns only not seen at all peers
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscovery.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
Labels: fix

#405 Remove node on negative declaration healthcheck
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: feature
