Repository Constellation-Labs/tessellation, pull requests merged in 2022-03, with the labels that each got.

#193 Use order syntax to compare heights
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotPreconditionsValidator.scala
Labels: other

#198 Genesis node starts global consensus with genesis snapshot
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
Labels: feature

#201 L0 download when joining
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/clients/GlobalSnapshotClient.scala
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/daemon/DownloadDaemon.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/node/NodeStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/daemon/NodeStateDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/node/NodeStorage.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: feature

#204 GlobalSnapshotStorage allows to start from any arbitrary snapshot
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
Labels: fix

#195 Global snapshot pulling in DAG L1
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/services/L0Service.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotOrdinalStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/clients/L0GlobalSnapshotClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/L0ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/L0ClusterStorage.scala
Labels: feature

#203 Simplify consensus state update
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
Labels: other

#205 Use F[Option instead of EitherT in local filesystem storage
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLocalFileSystemStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/shared/src/main/scala/org/tessellation/storage/FileSystemStorage.scala
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
Labels: other

#208 Validation of kryo registration IDs.
  examples/simple-snapshot-publisher/src/main/scala/org/example/GenerateInputApp.scala
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/core/src/test/scala/org/tessellation/domain/aci/StateChannelOutputGistedSuite.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/ext/kryo.scala
  modules/shared/src/main/scala/org/tessellation/kryo/KryoSerializer.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/test/scala/org/tessellation/kryo/KryoSerializerSuite.scala
  modules/shared/src/test/scala/org/tessellation/schema/TransactionSuite.scala
Labels: other

#210 Change BigInt into Long for balance
  modules/core/src/main/scala/org/tessellation/infrastructure/cluster/storage/AddressStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/genesis/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLocalFileSystemStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/address/storage/AddressStorage.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/TransactionValidator.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/transaction/TransactionValidatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/test/scala/org/tessellation/schema/BalanceSuite.scala
  modules/shared/src/test/scala/org/tessellation/schema/TransactionSuite.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/cli/method.scala
Labels: other

#215 Fix state-channel loader and update examples
  examples/l0-token/project/Dependencies.scala
  examples/l0-token/src/main/resources/state-channel-def
  examples/l0-token/src/main/scala/org/example/L0TokenDef.scala
  examples/simple-snapshot-publisher/project/Dependencies.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
Labels: fix

#213 Add AddressInfo and update LastTxRefs with Balances
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshotInfo.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: feature

#216 Peer declaration health-check
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/Daemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealth.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckDriver.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheckKey.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationProposalHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/node/NodeStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkStorages.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorageSuite.scala
Labels: feature

#217 Allow for compiling into docker image
  build.sbt
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
Labels: other

#219 Configurable state after joining process
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
Labels: fix

#220 Logback configuration for DAG L1
  modules/shared/src/main/resources/logback-included.xml
  modules/shared/src/main/resources/logback-mainnet.xml
  modules/shared/src/main/resources/logback-testnet.xml
  modules/shared/src/main/resources/logback.xml
Labels: fix

#222 Increase maxQueued elements for subscriptions
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/node/NodeStorage.scala
Labels: fix

#221 Do not start consensus when no tips available
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
Labels: fix

#223 DAG routes on L0 for balance and total supply
  modules/core/src/main/scala/org/tessellation/domain/dag/DagService.scala
  modules/core/src/main/scala/org/tessellation/http/routes/BlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/dag/DAGService.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
Labels: feature
