Repository Constellation-Labs/tessellation, pull requests merged in 2022-07, with the labels that each got.

#321 CORS support on public routes
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
Labels: feature

#322 Use plural in endpoints unless always a single entity
  modules/core/src/main/scala/org/tessellation/http/p2p/clients/GlobalSnapshotClient.scala
  modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/clients/L0GlobalSnapshotClient.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: fix

#326 Handling TimeTrigger & EventTrigger
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/SnapshotTrigger.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotPreconditionsValidator.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotTriggerPipeline.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/main/scala/org/tessellation/modules/Validators.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/PeerEvents.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/declaration/PeerDeclarationHealthCheck.scala
Labels: feature

#323 Implement rate limiting
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/config/ConsensusConfig.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/block/rumor/handler.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/TransactionGenerator.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/filter/Consecutive.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: feature

#327 Remove peers with not sufficient collateral after consensus
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotStorage.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/collateral/LatestBalances.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/daemon/CollateralDaemon.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
Labels: feature

#329 Fee param for Transaction Generator
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/TransactionGenerator.scala
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
Labels: ignore

#331 Add BUILD_VERSION arg to docker builds
  kubernetes/l0.Dockerfile
  kubernetes/l1.Dockerfile
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
  skaffold.yaml
Labels: other

#330 Fix invalid use of `foldMap` for combining facility data
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
Labels: fix

#334 Tool prints progress every 1s instead of every 100 tx
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
Labels: ignore

#332 Add test for collateral daemon
  build.sbt
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/daemon/CollateralDaemonSuite.scala
  project/Dependencies.scala
Labels: test

#337 Send blocks to L0 without tips and remove L1Output
  modules/core/src/main/scala/org/tessellation/domain/cell/AlgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/CoalgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/L0Cell.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/modules/Queues.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0DAGClusterClient.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/L1Output.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
Labels: fix

#335 Rumor validator
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Validators.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/collateral/Collateral.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorValidator.scala
  modules/shared/src/main/scala/org/tessellation/schema/id.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: fix

#339 Fix Order instances
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
  modules/shared/src/main/scala/org/tessellation/ext/cats/conversion/order.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
  modules/shared/src/main/scala/org/tessellation/schema/gossip.scala
  modules/shared/src/main/scala/org/tessellation/schema/height.scala
Labels: fix

#333 Add collateral verification during block acceptance
  build.sbt
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/domain/cell/L0CellSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceContext.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceLogic.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceManager.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockNotAcceptedReason.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/Tips.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/block/processing/BlockAcceptanceLogicSuite.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/domain/block/generators.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#341 Fix iterative acceptance of blocks
  modules/dag-shared/src/main/scala/org/tessellation/dag/block/processing/BlockAcceptanceManager.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/block/processing/BlockAcceptanceManagerSuite.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: fix, test

#343 Don't start genesis node without collateral
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/package.scala
Labels: feature

#324 Endpoint returning wallet-count
  modules/core/src/main/scala/org/tessellation/domain/dag/DagService.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/dag/DAGService.scala
Labels: feature

#344 Don't check collateral for own rumors
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
Labels: feature

#346 Rollback mechanism
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Session.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: feature

#349 POST /transactions returns the hash wrapped into an object
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
Labels: fix

#347 Print app version on startup
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
Labels: other

#351 Rename master to main branch
  doc/adr/0011-project-versioning-and-release-flow.md
Labels: ignore

#352 Use seed-list name
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Validators.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/seedlist/Loader.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/seedlist/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: other

#350 Add platform to docker build command
  skaffold.yaml
Labels: fix

#355 Add collateral daemon to L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
Labels: feature

#354 Periodic peer discovery on L1
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastGlobalSnapshotStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/L0ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/L0ClusterStorage.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/TransactionGenerator.scala
Labels: feature
