Repository Constellation-Labs/tessellation, pull requests merged in 2023-09, with the labels that each got.

#721 Persist genesis and first incremental during download
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/storages/SnapshotDownloadStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotDownloadStorage.scala
Labels: fix

#725 Changing metagraph dependencies generation in action
  .github/workflows/test-metagraph-rewards.yml
  .github/workflows/test-transactions.yml
Labels: other

#676 Verify pulled snapshots
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/StateChannel.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/services/GlobalL0Service.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/cli/env.scala
  modules/shared/src/main/scala/org/tessellation/ext/collection/FoldableOps.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
Labels: feature

#724 Peer selection takes trust value into account
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedProspect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedSampling.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedProspectSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedSamplingSuite.scala
Labels: feature

#720 Delay download until a selectable peer is found
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Daemons.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerDiscoveryDelay.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/daemon/DownloadDaemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/daemon/SelectablePeerDiscoveryDelay.scala
Labels: fix

#727 Add json with brotli compression serializer
  build.sbt
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/json/JsonBrotliBinarySerializer.scala
  modules/shared/src/test/scala/org/tessellation/json/JsonBinarySerializerSuite.scala
  modules/shared/src/test/scala/org/tessellation/json/JsonBrotliBinarySerializerSuite.scala
  project/Dependencies.scala
Labels: feature

#733 Always call combine when creating proposal artifact
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: fix
