Repository Constellation-Labs/tessellation, pull requests merged in 2023-04, with the labels that each got.

#610 Update trust info via gossip.
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
Labels: feature

#583 Fix joining errors
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/ClusterStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscoverySuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
Labels: fix

#613 Fix compilation of Constellation Tools
  build.sbt
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: fix

#618 Parametrize the last full global snapshot ordinal
  modules/core/src/main/scala/org/tessellation/cli/incremental.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/AppEnvironment.scala
Labels: feature

#594 Implement payloads endpoint
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/AccountIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Operation.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaSignature.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionMetadata.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionPayloads.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/generators.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/transaction/package.scala
Labels: feature

#596 Added CSV loader for trust ratings
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/domain/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/infrastructure/trust/storage/TrustDbValuesGenerator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/opts.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/trust/TrustRatingCsvLoader.scala
  modules/sdk/src/test/resources/ratings.sample.csv
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/trust/TrustRatingCsvLoaderSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/TrustValueRefinement.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: feature

#625 Implement metadata endpoint
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaPublicKey.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionMetadata.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionPayloads.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/generators.scala
Labels: feature

#623 Minimize Ref accesses in PeerDiscovery.discoverFrom
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/PeerDiscovery.scala
Labels: other

#628 Fix throwing error during consensus
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
Labels: fix

#627 Change Rosetta to use JSON serializer/deserializer
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
Labels: fix

#631 Add scala-cli to nix flake
  flake.nix
Labels: other

#621 Remove infrastructure dependency from Rollback and Genesis
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/genesis/Loader.scala
Labels: fix

#620 Download for incremental snapshots ADR
  doc/adr/0013-download-for-incremental-snapshots.md
Labels: adr

#630 Observe majority fork
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/programs/Download.scala
Labels: feature
