Repository Constellation-Labs/tessellation, pull requests merged in 2023-02, with the labels that each got.

#547 Updated logic for joining consensus
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ConsensusInfoRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusOutcome.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusResources.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateCreator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateRemover.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/info.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/message.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/registration.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/update/UnlockConsensusUpdate.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/FacilitatorCalculatorSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/consensus/update/UnlockConsensusUpdateSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/node.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: fix

#552 Adjust soft staking nodes February 2023
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#553 Fix discarding arbitrary instances for Signed
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Labels: test

#551 Rosetta - Derive public key endpoint
  build.sbt
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/AccountIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/NetworkIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaPublicKey.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionDerive.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/ext/http4s/refined.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
  modules/shared/src/main/scala/org/tessellation/ext/derevo/magnoliaCustomizable.scala
  modules/shared/src/main/scala/org/tessellation/security/Hex.scala
Labels: feature

#555 Remove hylo and stackF usage from L1 consensus
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/AlgebraCommand.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusOutput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/CoalgebraCommand.scala
Labels: other

#556 Format BlockConsensusCell class properly
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
Labels: other

#554 Store declarations that may be used in immediate future only
  modules/core/src/main/scala/org/tessellation/cli/snapshot.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
Labels: fix

#558 Add node to the mainnet seedlist
  mainnet/mainnet-seedlist
Labels: other

#560 Rosetta - Added the construction hash endpoint.
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/transaction/TransactionGenerator.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/TransactionIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionHash.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
Labels: feature

#561 Use blocking execution context for I/O file operations
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
Labels: fix

#563 Rewards distribution update
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/DTMDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/FacilitatorDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/ProgramsDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/SoftStakingDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/StardustCollectiveDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
  modules/shared/src/main/scala/org/tessellation/ext/refined/refined.scala
Labels: feature

#562 Added construction preprocess endpoint.
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Operation.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionPreprocess.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
Labels: feature

#570 Update of the data pool rewards address
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#572 Fix incorrect L1 BuildInfo
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
Labels: fix

#573 Add SubHeight to CurrencySnapshot
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/infrastructure/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
  modules/shared/src/main/scala/org/tessellation/schema/snapshot.scala
Labels: other

#574 Fix redirection for `/dag` routes
  modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/test/scala/org/tessellation/http/routes/DagRoutesSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/modules/HttpApi.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/CurrencyRoutes.scala
Labels: fix

#575 Include currencyL0 in root project
  build.sbt
Labels: fix

#567 Method for applying incremental snapshot to snapshot info
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/SnapshotStorageSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/infrastructure/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/shared/src/main/scala/org/tessellation/schema/GlobalSnapshot.scala
  modules/shared/src/main/scala/org/tessellation/schema/GlobalSnapshotTraverse.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
  modules/shared/src/main/scala/org/tessellation/tools/DAGBlockGenerator.scala
  modules/shared/src/main/scala/org/tessellation/tools/TransactionGenerator.scala
  modules/shared/src/test/scala/org/tessellation/schema/GlobalSnapshotTraverseSuite.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: feature

#568 Use traversing of incremental snapshot in rollback
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLoader.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotLoaderSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/SnapshotStorageSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/CurrencyApp.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/infrastructure/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/infrastructure/snapshot/CurrencySnapshotLoader.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/infrastructure/snapshot/CurrencySnapshotTraverse.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/modules/Storages.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/snapshot.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
Labels: feature
