Repository Constellation-Labs/tessellation, pull requests merged in 2023-06, with the labels that each got.

#649 DataApplication implementation for Currency L0
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cell/L0Cell.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Daemons.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Queues.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotEventsPublisherDaemon.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/package.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
Labels: feature

#659 Add locked addresses validation
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/TransactionValidator.scala
Labels: feature

#655 Expand SnapshotClient, use in MajorityPeerSelect
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/P2PClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/http/p2p/SnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/PeerResponse.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0SnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/SnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
Labels: fix

#662 Return all processed currency snapshots in global
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/shared/src/main/scala/org/tessellation/schema/GlobalSnapshotInfo.scala
Labels: feature

#663 Expose CurrencyL0App and CurrencyL1App
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/NoopRewards.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/Main.scala
Labels: feature

#667 Fix updating balances by rewards in Currency Framework
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
Labels: fix

#650 Change stateChannel's address to be generated from data'a hash
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/P2PClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/node/IdentifierStorage.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/storages/LastBinaryHashStorage.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/StateChannelSeedlist.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/StateChannelSnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkValidators.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelAcceptanceManagerSuite.scala
  modules/shared/src/main/scala/org/tessellation/ext/ciris/configDecoder.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
  modules/shared/src/main/scala/org/tessellation/schema/balance.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
  modules/shared/src/main/scala/org/tessellation/security/key/ops.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelSnapshotBinary.scala
  modules/shared/src/test/scala/org/tessellation/security/signature/SignedValidatorSuite.scala
Labels: feature

#669 Apply state incrementally during download
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
Labels: fix

#671 Fix purging snapshots from persisted storage
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/storages/SnapshotDownloadStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotDownloadStorage.scala
Labels: fix

#666 Added ip address, alias, and bias to the seedlist
  build.sbt
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Validators.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/seedlist.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateCreator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/seedlist/Loader.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/seedlist/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkPrograms.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkValidators.scala
  modules/sdk/src/test/resources/seedlists/seedlist.1field.sample
  modules/sdk/src/test/resources/seedlists/seedlist.4fields.sample
  modules/sdk/src/test/resources/seedlists/seedlist.invalid.sample
  modules/sdk/src/test/resources/seedlists/seedlist.mixedFields.sample
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/seedlist/LoaderSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: feature

#672 Return BadRequest in case of malformed state channel snapshot binary
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
Labels: fix

#677 New rewards minting logic starting July first
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/ProgramsDistributor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
Labels: feature

#678 Update mainnet seedlist
  mainnet/mainnet-seedlist
Labels: other

#675 Endpoint for accepting custom data blocks on Currency L0
  modules/core/src/main/scala/org/tessellation/http/routes/DAGBlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cell/AlgebraCommand.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cell/CoalgebraCommand.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cell/L0Cell.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/p2p/P2PClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/DataBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HealthChecks.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Download.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/p2p/L0CurrencyBlockOutputClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0BlockOutputClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/WalletRoutes.scala
Labels: feature
