Repository Constellation-Labs/tessellation, pull requests merged in 2023-12, with the labels that each got.

#788 Fetch latest snapshot info tool
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
  modules/tools/src/main/scala/org/tessellation/tools/cli/method.scala
Labels: ignore

#790 Use temp storage as cache instead of in-memory for data traverse
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/storage/TraverseLocalFileSystemTempStorage.scala
  modules/shared/src/main/scala/org/tessellation/schema/SnapshotOrdinal.scala
Labels: feature

#789 Updating l1 kryo registrar
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: fix

#792 Stop traversing when snapshots are invalid
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
Labels: fix

#793 Add check for snapshot info directory
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/snapshot.scala
Labels: fix

#795 Fix check for snapshot info directory
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/snapshot.scala
Labels: fix

#794 Github Workflow: Generate shared dependency first
  .github/workflows/test-metagraph-rewards.yml
  .github/workflows/test-transactions.yml
Labels: test

#791 Snapshot info cache for download program
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/domain/snapshot/storages/SnapshotDownloadStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotDownloadStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/programs/RollbackLoader.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
Labels: feature

#798 Initial SDK - SecurityProvider and Keypair generator as examples
  build.sbt
  modules/sdk/src/main/scala/org/tessellation/sdk/keytool/keypair/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/security/package.scala
Labels: feature

#801 Fix rosetta publish error
  build.sbt
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
Labels: fix

#804 Removing allowance list for Integrationnet
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
Labels: feature
