Repository Constellation-Labs/tessellation, pull requests merged in 2023-01, with the labels that each got.

#528 Adjust DTM weights
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#529 Adjust soft nodes January 2023
  modules/core/src/main/scala/org/tessellation/config/types.scala
Labels: other

#522 Add Rosetta classes, part 1.
  build.sbt
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/CoinIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Direction.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/NetworkIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/RelatedTransaction.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/SubNetworkIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/SyncStatus.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/TransactionIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Version.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/schema.scala
Labels: feature

#530 Flake configuration for nix shell
  .env
  build.sbt
  flake.lock
  flake.nix
  nix/ci.nix
  nix/config.nix
  nix/pinned.nix
  nix/pkgs.nix
  nix/sbt.nix
  shell.nix
Labels: other

#531 Extract state channels schema to shared module
  modules/core/src/main/scala/org/tessellation/domain/cell/AlgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/CoalgebraCommand.scala
  modules/core/src/main/scala/org/tessellation/domain/cell/L0Cell.scala
  modules/core/src/main/scala/org/tessellation/domain/statechannel/StateChannelService.scala
  modules/core/src/main/scala/org/tessellation/domain/statechannel/StateChannelValidator.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotEventsPublisherDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/package.scala
  modules/core/src/main/scala/org/tessellation/modules/Queues.scala
  modules/core/src/main/scala/org/tessellation/package.scala
  modules/core/src/test/scala/org/tessellation/domain/aci/StateChannelOutputGistedSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelServiceSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/Gistable.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/HypergraphContext.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/ProcessSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelBlock.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelContext.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelDef.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/StateChannelSnapshot.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelOutput.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelSnapshotBinary.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: other

#533 Remove unused or unnecessary constraints
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/transaction/ContextualTransactionValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/ConsensusHealthStatus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/rumor/handler.scala
Labels: other

#534 Update build badge
  README.md
Labels: ignore

#540 Log errors from state-channel runtime
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
Labels: other

#535 Added Rosetta classes, part 2.
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/AccountBalanceRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/AccountBalanceResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/AccountCoinsRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/AccountCoinsResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/AccountIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Amount.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/CallRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/CallResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Coin.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/ConstructionCombineRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/ConstructionCombineResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Currency.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/PartialBlockIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/PublicKey.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Signature.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/SignatureType.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/SigningPayload.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/SubAccountIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/schema.scala
Labels: feature

#541 Add Rosetta classes, part 3.
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Allow.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BalanceExemption.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Block.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockEvent.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockEventType.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockTransaction.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockTransactionRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/BlockTransactionResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/CoinAction.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/CoinChange.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/ExemptionType.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/MempoolResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/MempoolTransactionRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/MempoolTransactionResponse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/MetadataRequest.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/ModelCase.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Operation.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/OperationIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/OperationStatus.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/Transaction.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/schema.scala
Labels: feature

#544 Merkle tree implementation
  modules/shared/src/main/scala/org/tessellation/merkletree/MerkleTree.scala
  modules/shared/src/test/scala/org/tessellation/merkletree/MerkleTreeSuite.scala
Labels: feature

#539 Improve the mechanism for pulling blocks for acceptance on L1
  build.sbt
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockRelations.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockRelationsSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockServiceSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala
  modules/dag-shared/src/test/scala/org/tessellation/dag/domain/block/generators.scala
  modules/shared/src/main/scala/org/tessellation/security/Hash.scala
Labels: feature

#545 Added the models for the search endpoint
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/metadataSchema.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/schema.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/OperationStatus.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/Operator.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/SearchTransactionRequest.scala
Labels: feature
