Repository Constellation-Labs/tessellation, pull requests merged in 2023-03, with the labels that each got.

#576 Abstract L1 functionality and implement DAG L1
  modules/currency-l0/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockRelations.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusOutput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/http/p2p/clients/BlockConsensusClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/storage/ConsensusStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/DAGSnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/storage/LastSnapshotStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0CurrencyClusterClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0DAGClusterClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/block/rumor/handler.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HealthChecks.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Queues.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Validators.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockRelationsSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockServiceSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/Validator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/services/GlobalL0Service.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/storage/LastGlobalSnapshotStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/storage/LastSnapshotStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/ContextualTransactionValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/filter/Consecutive.scala
  modules/shared/src/main/scala/org/tessellation/schema/Block.scala
  modules/shared/src/main/scala/org/tessellation/schema/SnapshotReference.scala
  modules/shared/src/main/scala/org/tessellation/schema/block/DAGBlock.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
  modules/shared/src/main/scala/org/tessellation/shared/package.scala
Labels: feature

#578 Mainnet seedlist update
  mainnet/mainnet-seedlist
Labels: other

#580 Extract common part for currency to shared module
  build.sbt
  modules/currency-l0/src/main/scala/org/tessellation/currency/package.scala
  modules/currency-shared/src/main/scala/org/tessellation/currency/package.scala
  modules/currency-shared/src/main/scala/org/tessellation/currency/schema/currency.scala
Labels: other

#566 Added Rosetta's construction parse endpoint.
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionParse.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
Labels: feature

#582 Use GlobalL0PeerOpts instead of L0PeerOpts for Currency L0
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
Labels: fix

#584 Add apache 2.0 license
  LICENSE
  NOTICE
Labels: other

#586 Combine currency-shared into shared module
  build.sbt
  modules/shared/src/main/scala/org/tessellation/currency/cli/GlobalL0PeerOpts.scala
  modules/shared/src/main/scala/org/tessellation/currency/cli/L0TokenIdentifierOpts.scala
  modules/shared/src/main/scala/org/tessellation/currency/package.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
Labels: other

#590 Fix for unhandled errors on sending block from L1 to L0
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
Labels: fix

#595 Fix Signed unique signers validation
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
Labels: fix

#585 Added Rosetta's construction/combine endpoint.
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaPublicKey.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaSignature.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionCombine.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
Labels: feature

#604 Seedlist update
  mainnet/mainnet-seedlist
Labels: other

#600 Enhance global l0 service
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/services/GlobalL0Service.scala
Labels: feature

#599 Add data field to currency snapshot
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
Labels: feature

#598 Add fee field to currency snapshot
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelServiceSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelSnapshotBinary.scala
Labels: feature

#593 Add version field to snapshot
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/main/scala/org/tessellation/schema/GlobalSnapshot.scala
  modules/shared/src/main/scala/org/tessellation/schema/semver.scala
  modules/shared/src/main/scala/org/tessellation/schema/snapshot.scala
Labels: feature

#606 Merkle tree works for one leaf
  modules/shared/src/main/scala/org/tessellation/merkletree/MerkleTree.scala
  modules/shared/src/main/scala/org/tessellation/merkletree/syntax.scala
  modules/shared/src/test/scala/org/tessellation/merkletree/MerkleTreeSuite.scala
Labels: fix
