Repository Constellation-Labs/tessellation, pull requests merged in 2023-07, with the labels that each got.

#683 Data application - custom routes on currency L0 and L1
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication.scala
Labels: feature

#685 Data application context
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/DataBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Daemons.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/node/L0NodeContext.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotEventsPublisherDaemon.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/package.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/DataApplication.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/Main.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/ConsensusClient.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/ConsensusState.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Engine.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/p2p/L0CurrencyBlockOutputClient.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/p2p/P2PClient.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Programs.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Queues.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Services.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/node/L1NodeContext.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusInput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusOutput.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/RoundData.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/storage/ConsensusStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/L0BlockOutputClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/ConsensusInput.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/ConsensusOutput.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataCancellationReason.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
  modules/shared/src/main/scala/org/tessellation/schema/round.scala
Labels: feature

#686 Data application - check conflicting blocks
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Engine.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: feature

#687 Add integrationnet app environment
  modules/core/src/main/scala/org/tessellation/cli/incremental.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/NetworkIdentifier.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/networkapi/NetworkApiServiceSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/AppEnvironment.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/logs/LoggerConfigurator.scala
  modules/shared/src/main/resources/logback-integrationnet.xml
Labels: feature

#688 Add context to DataApplicationCustomRoutes
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: feature

#681 Adjust ProgramsDistributionConfig for future epoch
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/domain/dag/DagService.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/dag/DAGService.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala
  modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/TransactionValidator.scala
Labels: feature

#691 Check chain integrity when observing
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Download.scala
Labels: fix

#694 Add SecurityProvider to DataApplication context
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/node/L0NodeContext.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/node/L1NodeContext.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: feature

#695 Enable global snapshot processing if Data is enabled
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
Labels: fix

#696 Add last snapshot to L0NodeContext
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/node/L0NodeContext.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/node/L1NodeContext.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: feature

#693 Prevent transaction replayability attack
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/package.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Download.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Storages.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockServiceSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/block/processing/BlockAcceptanceContext.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/block/processing/BlockAcceptanceLogic.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/block/processing/BlockAcceptanceLogicSuite.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
Labels: fix

#697 Update mainnet seedlist
  mainnet/mainnet-seedlist
Labels: other

#698 Validation for historical state channel snapshots
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelServiceSuite.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelValidationType.scala
Labels: feature

#684 Added ordinal trust storage, service, and gossip
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/domain/cluster/programs/TrustPush.scala
  modules/core/src/main/scala/org/tessellation/domain/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugTrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustModel.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustStorageUpdater.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/HandlerSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/TrustModelSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/TrustStorageUpdaterSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/generators.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/storage/TrustStorageSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/Daemon.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/csv.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/OrdinalTrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/PublicTrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/DebugRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/trust/TrustRatingCsvLoader.scala
  modules/shared/src/main/scala/org/tessellation/schema/SnapshotOrdinal.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: feature
