Repository Constellation-Labs/tessellation, pull requests merged in 2023-05, with the labels that each got.

#634 Order currency snapshots before processing
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
Labels: fix

#638 Corrected skaffold dev command in docs
  SETUP.md
Labels: other

#619 Seedlist for state channels
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/StateChannelSeedlist.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/genesis/Loader.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkValidators.scala
  modules/shared/src/test/resources/logback-test.xml
Labels: feature

#636 PeerSelect gracefully handles no snapshot errors
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/programs/Download.scala
Labels: fix

#646 Fix PeerResponse URI creation
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/PeerResponse.scala
Labels: fix

#645 Process currency snapshots in correct order on GL0
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
Labels: fix

#633 Implement network api endpoints
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/NetworkIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Operation.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/network/NetworkApiList.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/network/NetworkApiOptions.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/NetworkApiError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/networkapi/NetworkApiService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/networkapi/model/options.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/networkapi/model/status.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/NetworkApiRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/networkapi/NetworkApiServiceSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/timestamp.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#647 Added logging to peer selection.
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
  modules/shared/src/main/resources/logback-included.xml
Labels: feature

#643 Added endpoint to get Snapshot hash
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/storage/SnapshotStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/SnapshotRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotStorage.scala
Labels: feature

#640 Update SETUP.md
  SETUP.md
Labels: fix

#652 Changed the client call to GET
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
Labels: fix

#651 Revisit P2P clients for response verifier middleware usage
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/P2PClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
Labels: fix

#654 Increase state channel snapshot size limit to 500kb
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
Labels: feature

#658 Update seedlist
  mainnet/mainnet-seedlist
Labels: other
