Repository Constellation-Labs/tessellation, pull requests merged in 2023-11, with the labels that each got.

#750 Recursively limit proposal size by returning excess blocks back to pool
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/block/processing/BlockNotAcceptedReason.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencyEventsCutter.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkValidators.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencyEventsCutterSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#760 Enable state channel public routes
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
Labels: feature

#759 Update README.md
  README.md
Labels: other

#766 Add allowance list for Testnet and IntegrationNet
  modules/core/src/main/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
Labels: other

#767 Add message to error classes that have data
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/LocalHealthcheck.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/shared/src/main/scala/org/tessellation/merkletree/MerkleTreeValidator.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
Labels: fix

#768 Improve rollback flow and logging
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
Labels: other

#770 Purge snapshots above during rollback
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/programs/RollbackLoader.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
Labels: feature

#757 Separate mode to generate genesis with address metadata
  .github/templates/metagraph_l0/genesis/action.yml
  .github/templates/metagraph_l0/ml0_cluster/action.yml
  .github/workflows/test-transactions.yml
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/SDK.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/opts.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/genesis/GenesisFS.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/genesis/Loader.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/genesis/GenesisFS.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/genesis/Loader.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/genesis/GenesisFSSuite.scala
Labels: feature

#773 Revert "Use trust scores in peer declarations selection"
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Services.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/storage/TrustStorageSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/seedlist.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/ProposalSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalOccurrenceSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalSelectWithFallback.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalTrustSelect.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalOccurrenceSelectSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalSelectWithFallbackSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalTrustSelectSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: fix

#774 Mainnet seedlist and allowance list update
  mainnet/mainnet-seedlist
  modules/core/src/main/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
Labels: other

#775 Set last full snapshot ordinal for mainnet environment
  modules/core/src/main/scala/org/tessellation/cli/incremental.scala
Labels: feature

#749 Added fork info handler and storage
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkDetect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfo.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoEntries.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/StoredForkInfo.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkDetect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoHandler.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkStorages.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkDetectSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoHandlerSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoStorageSuite.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/generators.scala
Labels: feature

#779 Change Data Application hook to return optional Resource
  .github/assets/basic_rewards_implementation.txt
  .github/templates/metagraph_l0/genesis/action.yml
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/Main.scala
Labels: fix

#780 Set calculated state only during consuming a majority snapshot
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
Labels: fix

#781 SnapshotInfo cache with logarithmic cutoff and new metagraph traverse
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotDownloadStorage.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/programs/RollbackLoader.scala
  modules/core/src/main/scala/org/tessellation/modules/Programs.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/SnapshotStorageSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/storage/TrustStorageSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/p2p/DataApplicationClient.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/snapshot.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotInfoLocalFileSystemStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotStorage.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/storage/CalculatedStateLocalFileSystemStorage.scala
  modules/shared/src/main/scala/org/tessellation/cutoff/LogarithmicOrdinalCutoff.scala
  modules/shared/src/main/scala/org/tessellation/cutoff/OrdinalCutoff.scala
  modules/shared/src/main/scala/org/tessellation/schema/SnapshotOrdinal.scala
  modules/shared/src/main/scala/org/tessellation/storage/FileSystemStorage.scala
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
  modules/shared/src/test/scala/org/tessellation/cutoff/LogarithmicOrdinalCutoffSuite.scala
Labels: feature

#782 Fix DataApplication traverse recursion loop
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
Labels: fix

#785 Only put unique valid data blocks in a snapshot
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
Labels: fix

#786 Update seedlist
  mainnet/mainnet-seedlist
Labels: other
