Repository Constellation-Labs/tessellation, pull requests merged in 2023-08, with the labels that each got.

#699 Return events without correct reference
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelAcceptanceManager.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelAcceptanceManagerSuite.scala
Labels: fix

#702 Retry sending state channel snapshot to global L0
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/StateChannelSnapshotClient.scala
  modules/shared/src/main/scala/org/tessellation/schema/package.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
Labels: fix

#700 Add EpochProgress to CurrencySnapshot
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/test/scala/org/tessellation/json/JsonBinarySerializerSuite.scala
Labels: feature

#701 Fix evidence and unused arguments warnings except encoder/decoder
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
  modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/HandlerSuite.scala
  modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/DataApplication.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/kernel/src/main/scala/org/tessellation/kernel/Cell.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/ext/http4s/refined.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/LastSnapshotStorage.scala
  modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelAcceptanceManagerSuite.scala
Labels: fix

#653 Additional validations for currency snapshot on Global L0
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Download.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/DAGSnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/SnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotValidator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/snapshot/currency.scala
Labels: feature

#705 Added model biases.
  modules/core/src/main/scala/org/tessellation/Main.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/DATT.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
  modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
  modules/core/src/main/scala/org/tessellation/modules/Storages.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/HandlerSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/TrustStorageUpdaterSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/trust/storage/TrustStorageSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: feature

#707 Log cause of failed download
  modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
Labels: other

#711 Currency L0 discovery process
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/StateChannel.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/services/GlobalL0Service.scala
Labels: feature

#710 Allow custom prefix for data-endpoints
  modules/core/src/main/scala/org/tessellation/http/routes/DAGBlockRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/DebugTrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/StateChannelRoutes.scala
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/DataBlockRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Engine.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/NetworkApiRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ClusterRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/ConsensusInfoRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/DebugRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/MetricRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/NodeRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/RegistrationRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/SnapshotRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/TargetRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/WalletRoutes.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusRoutes.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/ConsensusOutput.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
  modules/shared/src/main/scala/org/tessellation/http/routes/internal.scala
Labels: feature

#712 Isolated the trust rumor handlers logging
  modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
Labels: fix

#709 Exposed trust values to non-core services
  modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
  modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/p2p/P2PClient.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/p2p/P2PClient.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/OrdinalTrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/PublicTrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustMap.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0TrustClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/TrustClient.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
  modules/shared/src/main/scala/org/tessellation/schema/trust.scala
Labels: feature

#716 Check environment match during Joining process
  modules/core/src/main/scala/org/tessellation/cli/incremental.scala
  modules/core/src/main/scala/org/tessellation/cli/method.scala
  modules/core/src/main/scala/org/tessellation/config/types.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/core/src/main/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceLists.scala
  modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/core/src/test/scala/org/tessellation/infrastructure/statechannel/StateChannelAllowanceListsSuite.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/types.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/NetworkIdentifier.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/networkapi/NetworkApiService.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/ext/http4s/refined.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/NetworkApiRoutes.scala
  modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/networkapi/NetworkApiServiceSuite.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/Joining.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/services/Cluster.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/logs/LoggerConfigurator.scala
  modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
  modules/shared/src/main/scala/org/tessellation/cli/AppEnvironment.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/main/scala/org/tessellation/schema/peer.scala
Labels: fix

#717 Mock rewards (rewrite current to expected) when implementation not provided
  modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotValidator.scala
Labels: fix
