Repository Constellation-Labs/tessellation, pull requests merged in 2024-02, with the labels that each got.

#820 Updating mainnet-seedlist
  mainnet/mainnet-seedlist
Labels: other

#821 Updating mainnet-seedlist
  mainnet/mainnet-seedlist
Labels: other

#808 Joining & peer discovery finishes before download
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/cluster/programs/Joining.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/modules/SharedPrograms.scala
Labels: feature

#823 Resend multiple state channel binaries and increase retry ordinal delay.
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/StateChannel.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/SentStateChannelBinaryTrackingService.scala
  modules/currency-l0/src/test/scala/org/tessellation/currency/l0/snapshot/services/SentStateChannelBinaryTrackingServiceSuite.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/cli/method.scala
Labels: fix

#827 Adding READY condition to fetch snapshots using SnapshotRoutes
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/HttpApi.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/SnapshotRoutes.scala
Labels: feature

#805 Cut pulled GlobalSnapshotEvents, if necessary
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/snapshot/programs/Download.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/snapshot/programs/GlobalSnapshotEventCutter.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensus.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/snapshot/programs/GlobalSnapshotEventCutterSuite.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/cli/snapshot.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/config/types.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/event/EventCutter.scala
  modules/shared/src/main/scala/org/tessellation/schema/address.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelOutput.scala
Labels: feature

#831 Bump scala and sbt versions
  build.sbt
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HealthChecks.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/HealthChecks.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
  modules/keytool/src/main/scala/org/tessellation/keytool/Main.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/ClusterRoutes.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/healthcheck/LocalHealthcheck.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/logs/LoggerConfigurator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/resources/MkHttpClient.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/resources/MkHttpServer.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/block/generators.scala
  modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/storage/TraverseLocalFileSystemTempStorage.scala
  modules/shared/src/main/scala/org/tessellation/error/ApplicationError.scala
  modules/shared/src/main/scala/org/tessellation/merkletree/MerkleTreeValidator.scala
  modules/shared/src/main/scala/org/tessellation/schema/cluster.scala
  modules/shared/src/test/scala/org/tessellation/block/generators.scala
  modules/shared/src/test/scala/org/tessellation/merkletree/MerkleTreeSuite.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/transaction/io.scala
  project/Dependencies.scala
  project/build.properties
Labels: other

#834 Add locked address validation on transactions
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/transaction/ContextualTransactionValidator.scala
Labels: fix

#835 Updating Github action to use axios
  .github/action_scripts/check_clusters/shared.js
  .github/workflows/test-currency-transactions.yml
  .github/workflows/test-data-transactions.yml
  .github/workflows/test-metagraph-rewards.yml
Labels: other
