Repository Constellation-Labs/tessellation, pull requests merged in 2024-08, with the labels that each got.

#906 fix: changed /data response to match /transactions
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
  modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala
Labels: fix

#914 fix: changed /data response to match /transactions
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
Labels: fix

#916 ci: action for linting commit names and optional local hook
  .commitlintrc
  .github/workflows/pr-commits.yml
  .gitignore
  .husky/commit-msg
  flake.nix
  package-lock.json
  package.json
Labels: other

#918 feat: adding treasure wallets metanomics to be one time rewarded
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/config/types.scala
Labels: feature

#919 fix: update epoch progress one time reward to around 16 UTC 2024-08-08
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/config/types.scala
Labels: fix

#921 feat(seedlist): mainnet update
  mainnet/mainnet-seedlist
Labels: feature

#902 fix: explicitly set empty transaction refs for new destination addresses
  .github/action_scripts/send_transactions/currency.js
  .github/workflows/test-currency-transactions.yml
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorage.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
Labels: fix

#920 ci: automated release action
  .github/workflows/release.yml
Labels: other
