Repository Constellation-Labs/tessellation, pull requests merged in 2024-07, with the labels that each got.

#886 Config update for integrationnet
  modules/node-shared/src/main/resources/application.conf
Labels: other

#887 Fix rollback transition from GlobalSnapshotInfoV2
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/programs/RollbackLoader.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Programs.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
Labels: fix

#892 Adjust DataApplicationRoutes responses
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
  modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala
Labels: fix

#890 Adding validations to reject repeated owner or staking address
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyMessageRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelService.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Services.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelServiceSuite.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/FeeCalculator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencyMessageValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala
Labels: feature

#895 Updating integrationnet fee config
  modules/node-shared/src/main/resources/application.conf
Labels: fix

#897 Adding validations to reject repeated owner or staking address
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyMessageRoutes.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelService.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Services.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelServiceSuite.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/FeeCalculator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencyMessageValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidatorSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala
Labels: feature

#891 Fix GlobalSnapshotInfo storage
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/programs/RollbackLoader.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Programs.scala
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/SnapshotStorageSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotInfoLocalFileSystemStorage.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorageSuite.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/storage/TraverseLocalFileSystemTempStorage.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
  modules/tools/src/main/scala/org/tessellation/tools/Main.scala
Labels: fix

#898 Fix test data-transaction action
  .github/action_scripts/send_transactions/data.js
  .github/templates/project_template/modules/l0/src/main/scala/com/my/project_template/l0/custom_routes/CustomRoutes.scala
Labels: fix

#901 Unlock BitForex
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/ContextualTransactionValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockValidator.scala
Labels: fix

#899 Use given fee transactions if no data application available
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotValidator.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: fix

#894 Replace endpoint /data/validate with /data/estimate-fee
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/EstimatedFeeResponse.scala
  modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/EstimatedFee.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
Labels: feature

#903 Add TransactionFeeEstimator overridable with /transactions/estimate-fee route
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/TransactionRoutes.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Services.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/transaction/TransactionFeeEstimator.scala
Labels: feature

#907 Fix response type for /transactions/estimate-fee
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/TransactionRoutes.scala
Labels: fix

#909 Added badges for release version on TestNet/IntNet/MainNet
  README.md
Labels: ignore

#910 Updating Mainnet seedlist 31-07-2024
  mainnet/mainnet-seedlist
Labels: fix

#908 docs(adr): conventional commits
  doc/adr/0011-project-versioning-and-release-flow.md
  doc/adr/0015-conventional-commits.md
Labels: adr

#912 Include currencyL0 and currencyL1 into sdk module
  build.sbt
Labels: feature
