Repository Constellation-Labs/tessellation, pull requests merged in 2024-03, with the labels that each got.

#814 Add owner/stake to CurrencyIncrementalSnapshot
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/CurrencyMessageRoutes.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/services/CurrencyMessageService.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/CurrencyMessageStorage.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/http/routes/CurrencyMessageRoutesSuite.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/services/CurrencyMessageServiceSuite.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/CurrencyMessageStorageSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala
  modules/shared/src/main/scala/org/tessellation/security/signature/SignedValidator.scala
  modules/shared/src/test/scala/org/tessellation/schema/generators.scala
  modules/shared/src/test/scala/org/tessellation/security/signature/SignedValidatorSuite.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/cli/method.scala
  modules/wallet/src/main/scala/org/tessellation/wallet/file/io.scala
Labels: feature

#840 Set last ordinal for kryo-based hash for testnet
  modules/node-shared/src/main/resources/application.conf
Labels: other

#838 Reject transactions for address locked after a set ordinal
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Services.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockServiceSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockNotAcceptedReason.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockAcceptanceManagerSuite.scala
Labels: fix

#842 Reject transactions for address locked after a set ordinal
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Services.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala
  modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Services.scala
  modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/block/BlockServiceSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockNotAcceptedReason.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/block/processing/BlockValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockValidator.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/block/processing/BlockAcceptanceManagerSuite.scala
Labels: other

#843 Add brotli-native dependencies
  build.sbt
  project/Dependencies.scala
Labels: fix

#844 Update last kryo hash ordinal for testnet
  modules/node-shared/src/main/resources/application.conf
  modules/node-shared/src/main/scala/org/tessellation/node/shared/cli/hashLogic.scala
Labels: fix

#845 Cleanup above ordinal with fallback to kryo
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/SnapshotDownloadStorage.scala
  modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
Labels: fix

#846 Add CurrencyMessage to schema
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala
Labels: feature
