Repository Constellation-Labs/tessellation, pull requests merged in 2024-01, with the labels that each got.

#810 L0PeerDiscovery filtering out discovered peers who are not last facilitators
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/cluster/programs/L0PeerDiscovery.scala
Labels: fix

#813 Updating mainnet-seedlist
  mainnet/mainnet-seedlist
Labels: other

#807 Tracking pending state channel snapshot binaries with retry
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/StateChannel.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/SentStateChannelBinaryTrackingService.scala
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/currency-l0/src/test/scala/org/tessellation/currency/l0/snapshot/services/SentStateChannelBinaryTrackingServiceSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/cluster/programs/L0PeerDiscovery.scala
  modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala
  modules/shared/src/main/scala/org/tessellation/statechannel/StateChannelSnapshotBinary.scala
Labels: feature

#815 Enrich snapshot value passed into onSnapshotConsensusResult
  modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Labels: feature

#809 Added historical ordinal ranges field to seedlist
  modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
  modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelValidatorSuite.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/seedlist.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/seedlist/Range.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/seedlist/SeedlistEntry.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/seedlist/ranges.scala
  modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/seedlist/snapshotOrdinalTimeline.scala
  modules/node-shared/src/test/resources/seedlists/seedlist.4fields.sample
  modules/node-shared/src/test/resources/seedlists/seedlist.5fields.invalid.sample
  modules/node-shared/src/test/resources/seedlists/seedlist.5fields.sample
  modules/node-shared/src/test/resources/seedlists/seedlist.invalidFieldCounts.sample
  modules/node-shared/src/test/resources/seedlists/seedlist.mixedFields.sample
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/seedlist/RangeSuite.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/seedlist/RangesSuite.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/seedlist/generators.scala
  modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/seedlist/LoaderSuite.scala
  modules/shared/src/main/scala/org/tessellation/schema/SnapshotOrdinal.scala
Labels: feature

#817 Adding error handling on DataApplication runConsensus and sendBlockToL0
  modules/currency-l1/src/main/scala/org/tessellation/currency/l1/DataApplication.scala
Labels: fix
