Repository Constellation-Labs/tessellation, pull requests merged in 2025-05, with the labels that each got.

#1127 fix: adding Upsider AI metagraph to mainnet and updating seedlist
  mainnet/mainnet-seedlist
  modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/statechannel/StateChannelAllowanceLists.scala
Labels: fix

#1129 test: add e2e delegated staking tests
  .github/action_scripts/delegated_staking/delegated-staking.js
  .github/action_scripts/delegated_staking/keys/genesis-node.hex
  .github/action_scripts/delegated_staking/keys/validator-1-node.hex
  .github/action_scripts/node_parameters/node_parameters.js
  .github/action_scripts/shared/validations.js
  .github/workflows/e2e-functionality-tests.yml
  .github/workflows/test-delegated-staking.yml
  modules/node-shared/src/main/resources/application.conf
Labels: test

#1135 fix: updating GlobalSnapshotContextFunctions to remove invalid duplication detection
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
Labels: fix

#1136 feat: adding validation on cleanup function
  modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/SnapshotDownloadStorage.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala
Labels: feature

#1137 feat: changing from ++ to |+| when combining active delegated stakes
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DelegatedRewardsDistributor.scala
Labels: fix

#1131 test: working e2e for delegated stake with docker
  .gitignore
  docker/.env.example
  docker/Dockerfile
  docker/build-production.sh
  docker/docker-compose.local-bridge.yaml
  docker/docker-compose.profile-l0.yaml
  docker/docker-compose.test.yaml
  docker/docker-compose.yaml
  docker/entrypoint-dag-l0-join-coordinator.sh
  docker/entrypoint-dag-l1-join-coordinator.sh
  docker/entrypoint.sh
  test-scripts/delegated_stake_docker_test.sh
Labels: test

#1148 fix: validating state per block and setting last currency snapshot
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Programs.scala
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/programs/Download.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
Labels: fix

#1151 fix: updating state delegated state schema
  modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/http/routes/DelegatedStakesRoutes.scala
  modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/http/routes/NodeCollateralRoutes.scala
  modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/rewards/GlobalDelegatedRewardsDistributor.scala
  modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/rewards/GlobalDelegatedRewardsDistributorSuite.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/delegatedStake/UpdateDelegatedStakeValidator.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/nodeCollateral/UpdateNodeCollateralValidator.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DelegatedRewardsDistributor.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
  modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/delegatedStake/UpdateDelegatedStakeValidatorSuite.scala
  modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/nodeCollateral/UpdateNodeCollateralValidatorSuite.scala
  modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DelegatedRewardsDistributorSuite.scala
  modules/shared/src/main/scala/io/constellationnetwork/schema/GlobalSnapshotInfo.scala
  modules/shared/src/main/scala/io/constellationnetwork/schema/delegatedStake.scala
  modules/shared/src/main/scala/io/constellationnetwork/schema/nodeCollateral.scala
Labels: fix

#1155 feat: updating mainnet seedlist
  mainnet/mainnet-seedlist
Labels: feature

#1156 feat: updating mainnet configs
  modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/config/DelegatedRewardsConfigProvider.scala
  modules/node-shared/src/main/resources/application.conf
Labels: feature

#1157 fix: fixing lastTxnRefs validation
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
Labels: fix

#1163 fix: calling combine with empty updates
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
Labels: fix

#1153 feat: removing collateral check on context functions
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
  modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
  modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/block/BlockServiceSuite.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/block/processing/BlockAcceptanceLogic.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/block/processing/BlockAcceptanceLogic.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/block/processing/BlockAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotValidator.scala
  modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/infrastructure/block/processing/BlockAcceptanceLogicSuite.scala
  modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/infrastructure/block/processing/BlockAcceptanceManagerSuite.scala
Labels: feature

#1168 feat: adding helper logs to track spend transactions
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
Labels: feature

#1222 feat: adding peer selection to send currency snapshots
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/StateChannel.scala
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/CurrencySnapshotConsensusStateAdvancer.scala
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySender.scala
  modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelSnapshotService.scala
  modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySenderSuite.scala
Labels: feature

#1221 fix: updating configuration and adding logs
  modules/node-shared/src/main/resources/application.conf
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencyEventsCutter.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
  modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala
Labels: fix
